[FEAT] WriteNicknameViewController UI 및 TextField Delegate 구현
DeveloperAcademy-POSTECH/MC3-Team1-Hatnya pull request #20
Opened 2022-07-20 06:52 UTC by yeongwooCho

## 작업내용

- [x] nickname view UI
- [x] 한글자 이상 입력시에 입장 버튼 활성화

<img src="https://user-images.githubusercontent.com/48707024/179914735-6125ef13-b928-4a45-82dc-043d15e7d9c4.png" alt="hello world" width="200" /> <img src="https://user-images.githubusercontent.com/48707024/179914749-0d2dc16d-6bdf-4816-b907-97400321829f.png" alt="hello world" width="200" /> <img src="https://user-images.githubusercontent.com/48707024/179914764-a75ff17c-a189-4722-b11e-a0a6e2199784.png" alt="hello world" width="200" />

## 리뷰포인트

- 코드베이스 UI
- TextField delegate

## 다음으로 진행될 작업 
(2차 스프린트로 넘기게 되었다고 들었습니다)
 - 그룹 입장하면 입장한 사람 기존 파이어베이스의 스터디그룹에 추가하기
 - 입력과 동시에 글자 수 세서 표시해주기

2022-07-20 10:23 UTC, wonhui-kim approved these changes
감사합니다! 수고 많으셨어요

2022-07-20 10:47 UTC, MMMIIIN commented on Hatnya/Screens/WriteNickname/WriteNicknameViewController.swift
> +        guard let view = self.view else { return }
q;
<img width="228" alt="image" src="https://user-images.githubusercontent.com/78677571/179963889-dc88981a-8e25-49b1-862f-f89adda00ed8.png">
view가 강제언래핑 되고있어서 guard let으로 풀어준 건가요 ??

2022-07-20 11:18 UTC, MMMIIIN approved these changes
수고하셨습니당 ^______^

2022-07-21 01:57 UTC, Lia316 requested changes
역시 깔끔하고 꼼꼼한 비트 스타일이 돋보이는 PR이었습니다~ 👍🏻

익스텐션 파일 때문에 Request changes를 드렸는데, 
나중에 다른 사람이 수정하기 보다는 지금 수정하는 게 좋을 것 같아서 이렇게 드리게 되었습니다.

나머지는 비트께서 선택적으로 적용해주시면 좋을 것 같습니다! ^~^

2022-07-21 01:57 UTC, Lia316 commented on Hatnya/Screens/WriteNickname/WriteNicknameViewController.swift
> +}
p3;

extension 파일 분리 부탁드립니다!
파일분리를 하면, 다른 화면에서도 해당 기능이 쓰여서 재사용할 때 찾기 편할 것 같습니다

2022-07-21 01:57 UTC, Lia316 commented on Hatnya/Screens/WriteNickname/WriteNicknameViewController.swift
> +}
p4;

122번째 줄의 `width`의 변수명을 `borderWidth` 로 수정하면 어떨 지 제안드립니다!
`height: width` 를 보니 꼭 높이에 넓이를 주는 듯한 느낌이 들어서 말씀드립니다~

2022-07-21 01:57 UTC, Lia316 commented on Hatnya/Screens/WriteNickname/WriteNicknameViewController.swift
> +
p5;

이 부분에 혹시 린트 워닝 만나지 않으셨나요? 👀
저는 린트가 `Attributes Violation`을 말해줘서 수정했던 것 같아 여쭤봅니다 ^_^

2022-07-21 01:57 UTC, Lia316 commented on Hatnya/Screens/WriteNickname/WriteNicknameViewController.swift
> +        guard let view = self.view else { return }
[CCC-1st-AppStore-Bit PR 중 관련 내용](https://github.com/DeveloperAcademy-POSTECH/CCC-1st-AppStore-Bit) 첨부합니다~

2022-07-25 09:23 UTC, Lia316 approved these changes

2022-07-25 09:23 UTC, merged