[FEAT] JoinStudyView 구현
DeveloperAcademy-POSTECH/MC3-Team1-Hatnya pull request #21
Opened 2022-07-20 06:52 UTC by unuhqueen

## 작업내용

![Simulator Screen Shot - iPhone 13 - 2022-07-20 at 15 49 30](https://user-images.githubusercontent.com/49133245/179915724-42f58b79-764e-4d4d-b171-93c591db2701.png)
- [x] 제목 라벨과 텍스트 필드 구현
- [x] 텍스트 필드 6글자로 제한
- [x] 데이터 검색 기능 구현
- [x] 데이터 모델 및 샘플 데이터 구현

## 리뷰포인트
- 코드가 효율적인 코드인지

## 질문
- 검색 사항이 없을 때의 UI를 정하지 않았는데 이를 어떻게 할지

## 다음으로 진행될 작업
- PR 코드 리뷰
 - 다음으로 할 일을 적어주세요.

2022-07-20 11:23 UTC, MMMIIIN commented on Hatnya/Global/Supports/Info.plist
> +					<string>JoinStudyView</string>
p1;

작업하시면서 화면 확인하려고 한게 같이 커밋된 것 같아요 !

2022-07-20 11:26 UTC, MMMIIIN commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +class JoinStudyViewController: UIViewController, UITextFieldDelegate {
p3;

UITextFieldDelegate 는 extension으로 따로 빼는게 더 깔끔해 보이더라구요 !

```swift
extension JoinStudyViewController: UITextFieldDelegate
```

2022-07-20 11:30 UTC, MMMIIIN commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +    func checkMaxLength(textField: UITextField!, maxLength: Int) {
p2;

외부에서 접근하지 않는다면 private으로 설정해주세용 ^_____^

2022-07-21 01:23 UTC, unuhqueen commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +    func checkMaxLength(textField: UITextField!, maxLength: Int) {
넵~

2022-07-21 01:23 UTC, unuhqueen commented on Hatnya/Global/Supports/Info.plist
> +					<string>JoinStudyView</string>
앗 그렇네요! 고쳤습니다~

2022-07-21 01:23 UTC, unuhqueen commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +class JoinStudyViewController: UIViewController, UITextFieldDelegate {
감사합니다 반영했어요!

2022-07-21 06:43 UTC, Lia316 requested changes
이브 엄청 빠르게 구현하셨네요! 👍🏻👍🏻👍🏻 대단하십니다!
리뷰는 주로 질문과 가독성 개선 및 린트 수정으로 이루어져 있습니다! 
애매한 표현이나 궁금한 것 있으면 질문 주세요!!

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Global/Extension/UIButton+Extension.swift
> +}
q;

해당 메서드는 어떤 용도인가요? 👀

이름만 봤을 때는 버튼의 배경색을 바꿔주는 코드인 것 같아 보이는데, 
그렇다면 `button.backgroundColor = UIColor.anyColor` 정도의 코드면 충분하다고 생각합니다! 
혹시 어떤 어떤 용도일까요?

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Global/Resource/Base.lproj/LaunchScreen.storyboard
>                      </view>
q;

`LaunchScreen.storyboard`와 `Main.storyboard` 파일이 수정되었는데
현재 작업 배경에서는 수정될 일이 없어보여서
왜 수정됐는지 궁금합니다~! ^__^

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Global/Resource/Base.lproj/Main.storyboard
> +                        <color key="backgroundColor" systemColor="systemBackgroundColor"/>
q;

> LaunchScreen.storyboard와 Main.storyboard 파일이 수정되었는데
현재 작업 배경에서는 수정될 일이 없어보여서
왜 수정됐는지 궁금합니다~! ^__^

마찬가지로 질문 드립니다~

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Network/Models/Homework.swift
> +}
모델 작성 감사드립니다! 🤩✨✨

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Network/Models/Homework.swift
> +}
숙제 뷰는 제 작업 파일에 필요한 모델이었어서 저도 동일한 파일을 작성했는데
이런 부분은 서로 이슈를 파서 알려주면 좋겠다는 생각이 막 들었습니다..!

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Network/Models/StudyGroup.swift
> +}
오 모델에서 바로 익스텐션해서 목데이터를 만드셨군요👀
이것도 좋아보이네요!

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +    }
p4;

현재 프로퍼티 → 메서드 → 액션 메서드 → 생성자 → 메서드 등의 순서를 보이는데
따로 의도하신 게 아니라면 메서드와 프로퍼티를 기능 별로 묶어서 정리하는게 가독성이 더 좋을 것 같아서 코멘트 드립니다~!

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +}
p5;

메서드마다 줄바꿈 규칙이 일관적이지 않은 것 같습니다 😁

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +}
호호 이 코드는 텍스트 필드 화면을 맡으신 분이 모두 가지고 계시네요 🤣🤣
세 분께서 합의보셔서 삭제하거나 해야할 것 같네요~

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +            searchStudyGroup()
p5;

마찬가지로 익스텐션과 메서드 간의 줄바꿈이 일관적이지 않은 것 같습니다~!

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +        }
p3;

린트 워닝이 존재하네요..! 
색이 없는 것을 의도하셨다면 `.clear` 은 어떠신가요?

2022-07-21 06:43 UTC, Lia316 commented on Hatnya/Network/Models/StudyGroup.swift
> +}
p3;

린트 워닝 발견!
 
목데이터를 사용하는 것 때문에 줄이 길어지면 매개변수 마다 줄바꿈을 하여 린트 워닝을 해결할 수 있답니다~
또 다른 팁으로, 스트링이 길어지면 `"""` 을 사용하여 한 스트링 내에서도 줄바꿈을 할 수도 있답니다 ^0^

2022-07-21 06:58 UTC, Lia316 commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +
p5;

상단에 있는 주석에서 작성자와 날짜를 수정하는 것은 어떨지 의견드립니다~!

2022-07-21 07:24 UTC, Lia316 requested changes
p1;

`JoinStudyView.storyboard` 파일을 보니까, cancel 버튼 `x` 가 깨져서 보이지 않네요..!
스토리 보드 워닝까지 함께 있어서 고쳐주셨으면 합니다!

2022-07-22 01:56 UTC, unuhqueen commented on Hatnya/Global/Extension/UIButton+Extension.swift
> +}
요거는 버튼이 어떤 상태(normal, highlighted, disabled, selected)에 있냐에 따라 버튼의 색을 지정할 수 있는 extension 입니다!

2022-07-24 04:24 UTC, wonhui-kim commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +        } else if textField.text?.count ?? 0 > maxLength {
p0;

해당 부분 옵셔널이라 이렇게 구현하신 거라면
```swift
if let textLength = textField.text?.count {
    if textLength == maxLength {
        searchStudyGroup()
        nextButton.isEnabled = true
    } ...
}
```

이렇게 옵셔널 바인딩을 사용하면 좋을 것 같아요!

2022-07-24 04:24 UTC, wonhui-kim commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +        nextButton.setBackgroundColor(.systemGray6, for: .disabled)
p0;

설정하는 기능별로 함수를 따로 작성해서 viewDidLoad() 안에서는 함수를 호출해주면
가독성이 좋을 것 같아요 😁

2022-07-25 08:10 UTC, Lia316 commented on Hatnya/Global/Extension/UIButton+Extension.swift
> +}
아하 버튼의 상태에 따른 색 변화였군요! 답변 감사합니다~

2022-07-25 08:17 UTC, Lia316 approved these changes
수고하셨습니다~ 😁

2022-07-25 13:16 UTC, unuhqueen commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +    func checkMaxLength(textField: UITextField!, maxLength: Int) {
@MMMIIIN PR approve 해주심 감사하겠습니다~

2022-07-25 13:35 UTC, wonhui-kim approved these changes

2022-07-25 13:47 UTC, unuhqueen commented on Hatnya/Screens/JoinStudy/JoinStudyViewController.swift
> +        nextButton.setBackgroundColor(.systemGray6, for: .disabled)
@wonhui-kim 리뷰 전부 반영했습니다! Approve 부탁드려요 ^ㅅ^

2022-07-25 14:51 UTC, MMMIIIN approved these changes
고생많으셨습니다 ^______^

2022-07-26 00:10 UTC, merged