Feature/19 study list
DeveloperAcademy-POSTECH/MC3-Team1-Hatnya pull request #24
Opened 2022-07-21 15:10 UTC by wonhui-kim

## 작업내용

- [x] Table View 생성
- [x] Custom Cell 생성
- [x] navigation title, item 설정
- [x] Action Sheet 생성 후 + 버튼과 연결
- [x] 스터디 그룹 데이터 없을 경우 레이블 표시

<img src ="https://user-images.githubusercontent.com/96123303/180244392-6a7dd627-4575-46a2-a604-0ca42bffdf34.png" width="300">

## 리뷰포인트
 - 

## 질문
- lint warning 중 prohibited_interface_builder, strong_iboutlet 부분은 수정하는 것이 좋을까요?

## 다음으로 진행될 작업
 - 스토리보드로 작성한 것을 코드로 변경해보기

## 참고한 코드 출처
[셀 선택 UI 구현하기](https://ios-development.tistory.com/655)
[private IBOutlets](https://stackoverflow.com/questions/47310069/private-iboutlets-swift)

2022-07-22 00:30 UTC, MMMIIIN commented on Hatnya/Screens/StudyList/StudyListTableViewCell.swift
> +}
p2;

요건 Network/Models 로 빼주실 수 있나요 ??

2022-07-22 00:34 UTC, MMMIIIN commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +        emptyStudyLabel.textAlignment = .center
p3;

property는 viewDidLoad 밖에 따로 구분하면 훨씬 가독성이 좋을 것 같아요 !
```swift
    // MARK: - property

    let emptyStudyLabel = UILabel()
    emptyStudyLabel.text = "스터디 그룹이 없습니다."
    emptyStudyLabel.translatesAutoresizingMaskIntoConstraints = false
    emptyStudyLabel.font = .systemFont(ofSize: 17)
    emptyStudyLabel.textColor = .gray
    emptyStudyLabel.textAlignment = .center
```

요런 식으로요 !

2022-07-22 00:39 UTC, MMMIIIN commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +        }
p3;

요 친구도 화면을 그리는 하나의 함수를 만들어서 거기에다 작성하면 역할별로 코드가 나뉘어져서 팀원들이 코드 읽는데 조금은 더 편할 것 같아요 !

```swift
private func render() {
   ...
}
```

2022-07-22 00:52 UTC, MMMIIIN requested changes
전체적으로 외부에서 접근하지 않는 변수와 함수들은 private 부탁드립니다 ^_____^
수고많으셨습니다 !

2022-07-22 02:08 UTC, wonhui-kim commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +        emptyStudyLabel.textAlignment = .center
넵! 훨씬 가독성이 좋겠네요 수정하겠습니다~

2022-07-22 02:58 UTC, MMMIIIN commented on Hatnya/Network/Models/StudyGroup.swift
> +}
p4;

이 친구도 따로 파일을 만들어도 좋을 것 같아요 !

2022-07-24 04:33 UTC, wonhui-kim commented on Hatnya/Screens/StudyList/StudyListTableViewCell.swift
> +}
넵 [커밋](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/24/commits/239773cf2c043fa6d0967ade3207b162b4141eb4) 반영했습니다!

2022-07-25 08:13 UTC, MMMIIIN approved these changes
수고하셨습니다 ^_______^

2022-07-25 08:55 UTC, Lia316 requested changes
수고 많으셨습니다! 🙌🏻

변수명과 final 키워드만 수정하면 될 것 같습니다! ㅎㅎ

2022-07-25 08:55 UTC, Lia316 commented on Hatnya/Network/Models/StudyInfo.swift
> +   var desc: String
p4;

변수명을 줄이지 않고 명확하게 표현하는 것을 권장합니다~

2022-07-25 08:55 UTC, Lia316 commented on Hatnya/Screens/StudyList/StudyListTableViewCell.swift
> +
p3;

상속되지 않는 클래스라면 성능상의 이점과 명시적 효과 때문에 final 키워드를 쓰는 것이 좋습니다 😉

2022-07-25 08:55 UTC, Lia316 commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +    }
p3;

메서드명도 마찬가지로 줄여서 쓰기보다는 명확하게 표현해주는 것이 가독성에 더 좋습니다 ~!

2022-07-25 08:55 UTC, Lia316 commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +        }
p3;

마찬가지로 변수명이 의미를 담고 있었으면 좋을 것 같습니다~

그리고 print문으로 나중의 일을 적기보다는 린트 워닝이 있긴 해도 TODO 주석을 사용하는 편이
추후 유지 보수할 때 눈에 띄어 더 좋을 것 같다는 생각이 드네요..!

2022-07-25 08:55 UTC, Lia316 commented on Hatnya/Screens/StudyList/StudyListTableViewCell.swift
> +   }
🤩이 코드로 고민하던 문제를 해결하셨군요~! 👍🏻👍🏻

2022-07-25 08:55 UTC, Lia316 commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +    @IBAction private func showASBtn(_ sender: Any) {
p3;

마찬가지로, 위에 final 키워드 부탁드립니다~

2022-07-25 09:11 UTC, Lia316 commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +    }()
p4;

뷰 컴포넌트는 lazy var 로 사용하는 것을 권장합니다~

2022-07-25 12:50 UTC, wonhui-kim commented on Hatnya/Network/Models/StudyInfo.swift
> +   var desc: String
발견해주셔서 감사합니다! [커밋](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/24/files#diff-d5a938b11a460746d782e19b18af45b77a3beb00a044a5d776cba5eb66ea03a6R12) 반영했습니다!

2022-07-25 12:51 UTC, wonhui-kim commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +    }
아이고,, 이런 실수가 많네요 감사합니다! 
[커밋](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/24/files#diff-c1af9948564a59d3875c5e4452d50c035f9447199772d8df63638379af960e82R12) 반영했습니다!

2022-07-25 12:52 UTC, wonhui-kim commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +        }
그렇겠네요! 샘플 코드를 보고 따라하는 형식으로 하다보니 변수명 생각을 못했네요
발견해주셔서 감사합니다
[커밋](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/24/files#diff-c1af9948564a59d3875c5e4452d50c035f9447199772d8df63638379af960e82R43-R54) 반영했습니다!

2022-07-25 12:55 UTC, wonhui-kim commented on Hatnya/Screens/StudyList/StudyListTableViewCell.swift
> +   }
맞아요! 자꾸 외부 테이블 셀에서 해결하려고 했었는데 리아 덕분에 Debug view Hierarchy를 확인하고
컨텐트뷰 값을 바꾸는 것으로 해결했습니다
감사합니다 😻

2022-07-25 12:56 UTC, wonhui-kim commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +    }()
lazy var 를 사용함으로써 성능상의 이점이 있겠군요!
[커밋](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/24/files#diff-c1af9948564a59d3875c5e4452d50c035f9447199772d8df63638379af960e82R16-R24) 반영했습니다!

2022-07-25 13:01 UTC, wonhui-kim commented on Hatnya/Screens/StudyList/StudyListTableViewCell.swift
> +
궁금해서 찾아보았는데
final 키워드를 지정해주면 dynamic dispatch 방식 대신 static dispatch 방식이 사용되어 런타임 성능이 향상되는군요.
덕분에 알아갑니다! 감사합니다 리아 👍
[final 키워드 런타임 성능 향상 참고 자료](https://jellysong.tistory.com/122)

[커밋](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/24/files#diff-80c3158197b18cdbf00e5f329e224ad7fe7e40cee5057f387fce9d1b7f2a1618R10) 반영했습니다!

2022-07-25 15:00 UTC, wonhui-kim commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +    @IBAction private func showASBtn(_ sender: Any) {
[커밋](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/24/files#diff-c1af9948564a59d3875c5e4452d50c035f9447199772d8df63638379af960e82R12) 반영했습니다!

2022-07-26 01:45 UTC, Lia316 approved these changes
리뷰 반영 감사드립니다!!1

2022-07-26 01:49 UTC, Lia316 commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +    }()
맞습니다 호출되는 시점에서 생성되기 때문이죠~ 😁

2022-07-26 02:38 UTC, merged