Feature/13 create study view UI
DeveloperAcademy-POSTECH/MC3-Team1-Hatnya pull request #25
Opened 2022-07-21 23:11 UTC by kelly1422

## 작업내용
![simulator_screenshot_AD2A36EC-866E-4C06-9512-82B1E18F2417](https://user-images.githubusercontent.com/80809782/180329149-b4060690-c79b-41ef-93a1-2a6e80a33dba.png)

- [ ] 입력받는 것들 라벨과 텍스트필드 배치
- [ ] 피커로 1~4주 선택할 수 있도록
- [ ] 요일 버튼 나열
- [ ] 다음 버튼

## 리뷰포인트
커스텀하는 부분이나 들어가는 컴포넌트들이 생각보다 너무 많아서 최대한 뷰를 쪼개서 작성해보았는데, 어떤지 피드백 부탁드립니다, 
너무 쪼갰나 싶기도 하고🥲

## 질문
pr 작성중에 생각난건데 SceneDelegate에 제가 봐야할 뷰컨트롤러로 수정하고 푸쉬해버렸는데 이런경우엔 머지 전에 수정하면 될까요?

## 다음으로 진행될 작업
 - 선택한 주기 라벨에 업데이트하기
 - 다음버튼을 눌러 이동할 뷰컨트롤러 연결

## 참고한 코드 출처
커스텀뷰 제작 - https://tong94.tistory.com/18
delegate - https://roniruny.tistory.com/149

2022-07-22 00:57 UTC, MMMIIIN commented on Hatnya.xcodeproj/xcshareddata/xcschemes/Hatnya.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
p1;

이 파일이 커밋된 이유가 있을까요 ??
이 파일이 커밋되는건 잘 못본것 같아서요...
혹시 충돌을 일으킬까 우려되네요 ..

2022-07-22 01:00 UTC, MMMIIIN commented on Hatnya/Global/Extension/UIColor+Extension.swift
> +}
p2;

이 extension은 따로 UITextField+Extension을 만들어서 분리해주시겠어요 ??
UIColor+Extension에 다 모여있네요...ㅎㅎ

2022-07-22 01:01 UTC, MMMIIIN commented on Hatnya/Global/Extension/UIColor+Extension.swift
>  import Foundation
p2;

아마
```swift
import Foundation
```
이건 지워도 될거예요 !

2022-07-22 01:05 UTC, MMMIIIN commented on Hatnya/Global/Extension/UIColor+Extension.swift
> +}
p2;

이 친구를 포함한 아래의 다른 View의 extension들도 각 파일 젤 밑으로 옮겨주시겠어요 ??
Global적인 UIColor를 위한 extension파일이라...
다른 친구들은 해당파일 밑에 적어도 충분할 것 같아요 ! ^______^

2022-07-22 01:09 UTC, MMMIIIN commented on Hatnya/Global/Extension/UIColor+Extension.swift
> +extension CyclePickerView: UIPickerViewDelegate, UIPickerViewDataSource {
p4;

두 프로토콜을 각각 extension 분리하면 좋을 것 같아요 !
꼭 그래야 하는건 아닌데 분리하는게 더 깔끔해 보이더라구요 ^_______^
```swift
// CyclePickerView.swift

extension CyclePickerView: UIPickerViewDelegate {
    ...
}

extension CyclePickerView: UIPickerViewDataSource {
    ...
}
```

2022-07-22 01:24 UTC, MMMIIIN commented on Hatnya/Global/Supports/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
p2;

작업 하실 때 첫 화면을 확인하기 위해 한 세팅이 같이 커밋된 거 같아요 !

2022-07-22 01:25 UTC, kelly1422 commented on Hatnya.xcodeproj/xcshareddata/xcschemes/Hatnya.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
그러게요... 저게 뭘까요.. 찾아보니까

version="1.0"이것은 이 파일이 준수하는 XML 표준임을 의미
encoding="utf-8"파일이 UTF-8 유니코드 인코딩을 사용하여 인코딩됨을 의미한다고 하는데,

모든 XML 문서에 XML 선언이 필요한 것은 아니지만
그러나 XHTML 문서 작성자는 모든 문서에서 XML 선언을 사용하는 것이 좋다고 하는걸 보니,
필수적으로 필요한 부분은 아니지만, 크게 문제가 되진 않을거 같은데
어떻게 하면 좋을까요??

2022-07-22 01:25 UTC, kelly1422 commented on Hatnya/Global/Extension/UIColor+Extension.swift
> +}
넵 제가 잘 모르고 모든 extension을 저기다가 다 작성해버렸네요 하하 감사합니다!

2022-07-22 01:26 UTC, kelly1422 commented on Hatnya/Global/Extension/UIColor+Extension.swift
>  import Foundation
그렇군요 !! 수정하겠습니다~!!

2022-07-22 01:27 UTC, kelly1422 commented on Hatnya/Global/Extension/UIColor+Extension.swift
> +}
오호~~ global적인 코드만 따로 작성하는 거군요, 처음에 왜 extension을 따로 작성하는지 잘 몰랐는데, global적인 것들만 모아보면 훨씬 가독성이 좋겠네요 감사합니다!

2022-07-22 01:30 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +    var selectedDays: [String] = [""]
p3;

현재 
```swift
var selectedDays: [String] = [""]
```
이 친구가 사용되고있지 않은 것 같은데 혹쉬,, 남겨둔 이유가 있을까요...??

2022-07-22 01:32 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +        let safeArea = view.safeAreaLayoutGuide
오호.. 코드를 줄이기 위해서 하신 방법인가요 ??
한 수 배웠습니다.. ^_____^

2022-07-22 01:32 UTC, kelly1422 commented on Hatnya/Global/Extension/UIColor+Extension.swift
> +extension CyclePickerView: UIPickerViewDelegate, UIPickerViewDataSource {
오호 그럴수도 있겠군요! 그런데 저 두 기능이 모두 picker의 기능을 위해 필요한 것이라 생각해 묶어서 작성한거긴 한데, 생각해보니 나눠 쓰는게 더 좋을거 같아요

(그런데 다시 확인해보니 오버라이드한 모든 함수가 UIPickerViewDelegate에 포함되어 있는 것들이라.. UIPickerViewDataSource 프로토콜은 전혀 사용되지 않고 있었네요, 없애도 되는 코드인거 같아 없애고 다시 커밋하겠습니다! )

2022-07-22 01:33 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +import SwiftUI
p1;

이건 젤 위로... 🙏

2022-07-22 01:35 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +    var selectedDays: [String] = [""]
아직 아래에 주기를 선택할때마다 업데이트할 라벨 부분을 구현하기 위해 만들었던 건데, 2차 스프린트로 넘어갈거 같아 그와 관련된 코드들은 다 주석 처리하고 커밋하도록 하겠습니다~!!

2022-07-22 01:36 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +        let safeArea = view.safeAreaLayoutGuide
코드도 줄고, 작성 시간도 줄고, 가독성이 좀 더 좋아지는 느낌이더라구요 ^________^

2022-07-22 01:36 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +    }
p3;

혹시 이게 preview를 보기 위함이라면
```swift
struct CreateStudyViewControllerPreview: PreviewProvider {

    static var previews: some View {
        CreateStudyViewController().toPreview()
    }

}
```

요렇게해도 될 것 같아요 ! ^_______^

2022-07-22 01:38 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +import SwiftUI
앗 프리뷰에만 필요하다고 생각해 저렇게 해놨는데 import는 모아두는게 좋겠군요... 👌

2022-07-22 01:40 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    let cycles = ["1", "2", "3", "4"]
p4;

```swift
enum CyclePickerView: String, CaseIterable {
    case one = 1
    ...
}
```
이런식은 어떨까요 ??

2022-07-22 01:41 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    }()
p3;

요 친구만 ```var``` 인 이유가 있을까요 ??
상관이 없다면 ```let``` 으로 통일 가능할까요 ??
아니면 리아의 말대로 ```lazy var```로 통일하는 것도 괜찮고요 !

2022-07-22 01:43 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +    }
오호! 넵 리아가 작성한 부분을 pull 받지 않아서 저렇게 해놓았는데, 
바꾸고 다시 커밋하는게 좋을까요 아니면 일단 돌아가는 상태로 머지한뒤 수정하는게 좋을까요??

2022-07-22 01:44 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    }
p3;

오잉 여기서 LintError를 피하셨나요 ??
전 못피해서 ...
```suggestion
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
```
아마 요렇게 하면 될겁니다 !

2022-07-22 01:47 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    }
흠 LintError가 혹시 노란 줄로 나타나는 거라면 발생하지 않은거 같은데..!

<img width="254" alt="스크린샷 2022-07-22 오전 10 46 04" src="https://user-images.githubusercontent.com/80809782/180343852-d4b6936f-4856-432a-88de-54218763a9df.png">
<img width="610" alt="스크린샷 2022-07-22 오전 10 45 10" src="https://user-images.githubusercontent.com/80809782/180343745-5de3c6ae-a4f5-49b3-8332-a725e8a78e8e.png">

그래도 수정하는게 좋을까요? 아니면 혹시 제가 린트에러를 발견 못하고 있는걸까요?

2022-07-22 01:48 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +        pickerView.isHidden = true
p3;

이 두친구는 ```render()```의 결과 조금 다른 것 같아요
```swift
private func configUI() {
    pickerView.delegate = self
    pickerView.isHidden = true
}
```
다양한 방법이 있겠지만, 이게 조금은 더 분리가 된 느낌인 것 같아요 !

2022-07-22 01:50 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    }()
어머 바로 let으로 수정하였습니다!
아직 lazy 속성에 대해 잘 몰라서 공부해고 다음부터 lazy var를 적용해보도록 하겠습니다!

2022-07-22 01:51 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonStackView.swift
> +        self.spacing = 0
p4;

이 방법도 좋지만, 비슷한 성격인 것 같은데 이 친구들을 한 곳에 모은 함수를 만드는 것도 괜찮을 것 같아요 ! ^_____^

2022-07-22 01:51 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonStackView.swift
> +    }
p3;

요 친구도 위에서 말씀드린 것 처럼 바꿀 수 있습니당 ^_____^

2022-07-22 01:52 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +    var  isClicked = false
p1;

아앗... 띄어쓰기가 ...
```suggestion
    var isClicked = false
```

2022-07-22 01:54 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +        self.frame(forAlignmentRect: CGRect(x: 0, y: 0, width: 32, height: 32))
p4;

```swift
private func configUI() {
    self.backgroundColor = .systemBackground
    self.setTitleColor(UIColor.systemBlue, for: .normal)
    self.titleLabel?.font = UIFont.systemFont(ofSize: 20)
    self.layer.cornerRadius = 16
    self.addTarget(self, action: #selector(buttonTouch), for: .touchUpInside)
    self.frame(forAlignmentRect: CGRect(x: 0, y: 0, width: 32, height: 32))
}
```

이렇게 분리할 수 있을 것 같아요 ..!! 😁

2022-07-22 01:58 UTC, unuhqueen commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +    var selectedDays: [String] = [""]
2차 sprint로 넘기는 주석 처리하실 때는 `// TODO: 어쩌구저쩌구` 이런식으로 주석 남겨주시면 좋을 것 같아요!

2022-07-22 01:58 UTC, unuhqueen commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +        let safeArea = view.safeAreaLayoutGuide
웃음이 더 길어져써요 ^______________^

2022-07-22 01:59 UTC, MMMIIIN reviewed
제로 화이팅..!! 😆

2022-07-22 02:00 UTC, unuhqueen commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +    }
어차피 merge conflict가 있으니 pull하시고 케미가 리뷰한 부분으로 바꾸고 커밋하는게 좋을 것 같아요!!

2022-07-22 02:01 UTC, kelly1422 commented on Hatnya/Global/Supports/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
원래대로 돌려놓도록 하겠습니다~!!

2022-07-22 02:24 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    let cycles = ["1", "2", "3", "4"]
아직 저에겐 enum이 넘나 어려워서.. 익숙해지지 않더라고요,, 혹시 기회가 된다면 케미라면 어떻게 코드를 작성할지 배우고 싶습니다!!!

2022-07-22 02:26 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +    var selectedDays: [String] = [""]
오 다음에 알아보기 더 쉽겠네요! todo 내용도 함꼐 주석으로 달아놓겠습니다!!

2022-07-22 02:28 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +    }
오호 당장 풀하고 수정해보겠습니다~!!

2022-07-22 02:30 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +        self.frame(forAlignmentRect: CGRect(x: 0, y: 0, width: 32, height: 32))
케미의 피드백 덕분에 render, configUI 함수에 넣어야 할 코드들의 성격에 대해 감이 좀 오는군요 앞으로는 잘 분리해서 작성해보겠습니다!

2022-07-22 02:59 UTC, MMMIIIN commented on Hatnya.xcodeproj/xcshareddata/xcschemes/Hatnya.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
이미 올라갔지만 혹시 이 파일 자체를 빼고 커밋할 순 없을까요...??

2022-07-22 14:05 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +        pickerView.isHidden = true
수정했습니다!
625bcded0869e17bca675d097086eebcc2f4ded7

2022-07-22 14:07 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonStackView.swift
> +        self.spacing = 0
StackView를 extension해서 저런 속성을 따로 하나의 함수로 작성하라는 의미인가요??!

2022-07-22 14:09 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +    var  isClicked = false
어이쿠야! 제거했습니다 ㅎㅎ
5426e2ba3f1063323b7e975f74676d8bc5212eb1

2022-07-23 09:55 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    }
전 빨간줄로 나는 에러였어요 ..!
fatalError가 앱을 강제로 종료시키는 함수라 린트에서 막는 것 같더라구요 !

2022-07-23 09:59 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonStackView.swift
> +        self.spacing = 0
저 네 친구가 같은 성격의 역할 같아서 하나의 함수로 만들면 어떻겠냐는 얘기였어요 !
만약 저게 StackView의 설정을 하는 메소드들이었다면
```swift
private func setupStackView() {
    self.axis = .horizontal
    self.alignment = .center
    self.distribution = .equalSpacing
    self.spacing = 0
}
```
이런식으로 하나의 함수에 묶어두고 다른곳에서 호출하는 방식은 어떨까요 ??!
팀원이 봤을 때 이해하는데 도움이 될 것 같아요 ! ^_____^

2022-07-23 10:07 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    let cycles = ["1", "2", "3", "4"]
List와 enum 둘 다 여러 정보들을 저장할 수 있는데 List는 append()를 통해 추가가 가능하고 enum은 절대 추가할 수 없는게 핵심인 것 같아요 ! 저희가 얘기했을때 스터디 반복 주기를 최대 4주로 하자고 했으니 1, 2, 3, 4 밖에 없을 것 같아서요 !
List로 만들어둬도 사용자 입장에서 추가할 수 없는건 사실이지만, 더 안전하고 명확히 하기위해 enum을 사용하는 것 같아요 !
enum의 case들을 배열처럼 사용하기 위해 CaseIterable 라는 프로토콜을 따르는거구요 !
다음에 기회가 된다면 같이 한번 고쳐봅시다 ! ^_______^

2022-07-25 06:18 UTC, kelly1422 commented on Hatnya.xcodeproj/xcshareddata/xcschemes/Hatnya.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
[cee8c9a](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/cee8c9a3e93b505004784caec73fd66ed8577551)
삭제완료!!

2022-07-25 08:57 UTC, MMMIIIN commented
@kelly1422 fatalError 부분 수정하시면 어푸르브 하겠슴당

2022-07-25 09:10 UTC, Lia316 requested changes
수고하셨습니다!

- final 
- lazy var
- lint warning & error

위주로 리뷰 남겼습니다!

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    }
p2;

해당 부분은 fatalError 대신 내용을 채워넣길 권장하는 거라 수정하시면 좋을 것 같습니다!

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +        stackView.spacing = 10
p4;

view component들은 lazy var 키워드를 권장합니다 🙂

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +
p4;

상단 클래스에 final키워드 부탁드립니다! 
성능상의 이점과 명시성이 보장된답니다~

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +
p3;

해당 메서드를 사용하는 곳의 익스텐션에 상속을 명시해주면 좋을 것 같습니다!

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +class DayButtonView: UIButton {
p3; 

상속받지 않는 클래스라면 final 키워드 부탁드립니다!

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +    }
p2;

fatalError 제거 부탁드립니다!

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +    @objc func buttonTouch() {
p4;

린트 적용이 안 된 코드 스타일인 것 같습니다..!

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +            self.titleLabel?.font = UIFont.boldSystemFont(ofSize: 20)
p5;

self 키워드는 언제 쓰면 좋을까요? 👀

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/GetInfoView.swift
> +    }()
p4;

final & lazy var

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/GetInfoView.swift
> +    }
p2;

lint error

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/SelectCycleDaysView.swift
> +//    }()
p3;

사용하지 않는 코드라면 삭제 부탁드립니다!

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/SelectCycleDaysView.swift
> +    let dayButtonStackView = DayButtonStackView()
p3;

final & lazy var

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/SelectCycleDaysView.swift
> +    }
p2;

lint error

2022-07-25 09:10 UTC, Lia316 commented on Hatnya/Global/Extension/UITextField+underline.swift
> +}
해당 부분은 비트도 올리셔서 수정을 요청드렸던 부분이라
삭제하고 비트 코드를 머지해도 좋을 것 같습니다!

2022-07-25 11:21 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    let cycles = ["1", "2", "3", "4"]
정확합니다! 
원하는 범위가 이렇게 명확한 경우에는 열거형을 통해서 제한하는 것이 예상치 못한 버그를 줄이고, 
의도도 더 잘 나타낼 수 있어 좋습니다!

2022-07-25 16:17 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/SelectCycleDaysView.swift
> +    }
[63b5c34](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/63b5c34dd3049cad54db3e14d511adacb43919dc) 
수정완료!!

2022-07-25 16:17 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/GetInfoView.swift
> +    }
[63b5c34](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/63b5c34dd3049cad54db3e14d511adacb43919dc) 
수정완료!!

2022-07-25 16:21 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +        stackView.spacing = 10
[0a99e5e](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/0a99e5e22210733728e5650231cc260a79a7955e)
수정완료!

2022-07-25 16:23 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/SelectCycleDaysView.swift
> +//    }()
[49be272](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/49be272aaf3d5e087fde0cf2be46383da8a6350c)
수정완료!!

2022-07-25 16:26 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/SelectCycleDaysView.swift
> +    let dayButtonStackView = DayButtonStackView()
[457c511](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/457c511bbe9835ad14fa675c6959513c5893f085)
수정완료!

2022-07-25 16:26 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +class DayButtonView: UIButton {
[457c511](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/457c511bbe9835ad14fa675c6959513c5893f085)
수정완료!!

2022-07-25 16:26 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +
[457c511](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/457c511bbe9835ad14fa675c6959513c5893f085)
수정완료!

2022-07-25 16:29 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +    }
[63b5c34](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/63b5c34dd3049cad54db3e14d511adacb43919dc)
수정완료!!

2022-07-25 16:30 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/GetInfoView.swift
> +    }()
[457c511](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/457c511bbe9835ad14fa675c6959513c5893f085)
수정완료!

2022-07-26 00:14 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +
[8b57407](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/8b57407c6badc69615c4930f5b7be1d070e625b5)
수정완료 했습니다!!

2022-07-26 00:18 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +            self.titleLabel?.font = UIFont.boldSystemFont(ofSize: 20)
제가 알고있는 건 보통 외부에서 받아들이는 변수명과 내부 변수명이 같아서 이해하기 어려울때 내부변수에 self 를 쓰는 경우입니다. 생각해보니 저런부분에는 self 키워드가 필요 없을거 같네요!

혹시 이 밖에도 self가 필요한 부분이 있을까요?

그리고 그렇다면 저 부분에서 사용한 self는 삭제하는 것이 더 좋을까요??!

2022-07-26 00:30 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +    @objc func buttonTouch() {
[32e5c20](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/32e5c2040703ca2db2124dd838e0465b79348ac1)
수정 완료 했습니다~!!

2022-07-26 01:09 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +    }
[63b5c34](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/63b5c34dd3049cad54db3e14d511adacb43919dc)
수정 완료했습니다!!

2022-07-26 01:09 UTC, kelly1422 commented on Hatnya/Global/Extension/UITextField+underline.swift
> +}
[2d811dd](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/2d811dd5889f064f941dab203589ead0c4023a7f)
머지 완료했습니다!

2022-07-26 01:51 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +        stackView.spacing = 10
p3;

private 키워드가 사라졌네요..?! 🫣

2022-07-26 01:58 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +        stackView.spacing = 10
다시 추가했습니다 하하 private 까지 다 빼고 lazy var를 사용하는줄 알았어요 .. ㅎ하ㅎ
[ed1349f](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/ed1349f40ba29fce3f11038296782a6b4ff67e16)

2022-07-26 01:59 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +            self.titleLabel?.font = UIFont.boldSystemFont(ofSize: 20)
네 맞습니다!
추가로 객체 안에 클로저를 생성할 때도 self로 접근해야하기도 합니다.

말씀해주신 이유와 위의 이유를 제외하고는 가독성을 위해 self를 많이 생략하는 편입니다.

이는 스타일의 차이가 있을 수 있으니 제안 정도만 드려요..!

2022-07-26 02:00 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/GetInfoView.swift
> +    }()
마찬가지로 private 키워드가 사라져서 적용 부탁드립니다!

2022-07-26 02:03 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/CyclePickerView.swift
> +
😆🙌🏻🙌🏻

2022-07-26 02:04 UTC, Lia316 requested changes
리뷰 반영해주셔서 감사합니다!
private 키워드가 사라진 부분만 다시 수정해주시면 머지할 수 있을 것 같습니다~!

2022-07-26 02:07 UTC, kelly1422 commented
> 리뷰 반영해주셔서 감사합니다! private 키워드가 사라진 부분만 다시 수정해주시면 머지할 수 있을 것 같습니다~!

중간에 private을 삭제하면 안된다는걸 깨닫고 다시 추가했는데 리뷰 댓글에 포함하지 않았네요!
[ed1349f](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/25/commits/ed1349f40ba29fce3f11038296782a6b4ff67e16)
여기에서 다시 추가해두었습니다

꼼꼼한 리뷰 감사해용👍

2022-07-26 02:14 UTC, Lia316 approved these changes

2022-07-26 02:22 UTC, MMMIIIN approved these changes
ㅋㅋㅋㅋ 진짜 수고 많으셨습니다 ^______^

2022-07-26 02:25 UTC, merged