[FEAT] 숙제 목록 편집 화면
DeveloperAcademy-POSTECH/MC3-Team1-Hatnya pull request #31
Opened 2022-07-25 08:44 UTC by Lia316

## 작업내용
- [x] 테이블 뷰 레이아웃
- [x] 테이블 뷰 셀 편집 모드
- [x] 숙제 추가 기능
- [x] + 버튼 누르면 모달 띄우기
- [x] 완료 누르면 모달 해제

## 리뷰포인트
- 새로운 숙제 추가 부분
  - `tableView delegate`로는 셀 추가 시 바로 반영이 되지 않아 푸터 뷰로 해결하였습니다.
  - 대신에 뷰 간 데이터 이동을 combine을 사용하여 했습니다.
- 뷰 전환 부분
  - StudyRoomViewController 에서 EditTaskViewController로 넘어가기 위한 버튼이 서브뷰 안에 있어 델리게이트로 처리했습니다.

## 다음으로 진행될 작업
 - 파이어베이스 연결

## 참고한 코드 출처
- Modern Collection View

2022-07-25 09:29 UTC, MMMIIIN commented on Hatnya/Screens/StudyRoom/StudyRoomViewController.swift
> +final class StudyRoomViewController: UIViewController {
q:

final을 붙이는 큰 이유가 더이상 상속을 불가능하게하기 위함인걸로 아는데,
final 키워드를 안붙이고 상속을 안하면 그만이지만 현재는 더이상 상속되지 않을것이기 때문에 final을 사용함으로써 더 명확히 하기위함인가요??

2022-07-25 09:36 UTC, MMMIIIN reviewed
diffable과 comine... 모르는 개념이 두개나 있어서 공부를 하고 리뷰를 남겨야겠어요.. ^________^

2022-07-25 11:13 UTC, Lia316 commented on Hatnya/Screens/StudyRoom/StudyRoomViewController.swift
> +final class StudyRoomViewController: UIViewController {
final 키워드를 붙이게 되면, 컴파일러가 컴파일 타임에 어떤 메서드를 불러야할 지 알게 되지만,
붙이지 않으면 상속의 가능성이 있기 때문에 런타임에 불러야할 메서드를 결정해야 해서 성능상의 단점이 있습니다.

추천드릴 키워드는 `method dispatch in swift` 이며, 
참고하면 좋을 곳은 [애플 공식 블로그 -Increasing Performance by Reducing Dynamic Dispatch ](https://developer.apple.com/swift/blog/?id=27) 입니다

2022-07-25 13:34 UTC, wonhui-kim requested changes

2022-07-25 13:34 UTC, wonhui-kim commented on Hatnya/Screens/EditTask/UIComponent/EditTaskSupplementaryView.swift
> +        ])
[이전 pr 고차함수](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/22#discussion_r928192591)

p4;
이 부분도 고차함수를 적용해서 조금 더 간결한 코드로 만들 수 있을 것 같아요!

2022-07-25 13:34 UTC, wonhui-kim commented on Hatnya/Screens/StudyRoom/UIComponent/HomeworkListTitleView.swift
> +    }
혹시 의도하신 개행일까요?!

2022-07-25 13:34 UTC, wonhui-kim commented on Hatnya/Screens/EditTask/EditTaskViewController.swift
> +        self.navigationController?.navigationBar.backgroundColor = .systemBackground
여기도 작성하신 다른 함수들과 달리 첫행이 개행되어있네요!
혹시 발견 못하신 실수일까봐 코멘트 남깁니다 😁

2022-07-25 14:35 UTC, MMMIIIN commented on Hatnya/Screens/StudyRoom/StudyRoomViewController.swift
> +final class StudyRoomViewController: UIViewController {
와우 ! 한 수 배워갑니다 ^______^

2022-07-26 00:06 UTC, Lia316 commented on Hatnya/Screens/StudyRoom/UIComponent/HomeworkListTitleView.swift
> +    }
앗 필요없는 코드를 삭제하다 보니 의도치 않은 개행이 나온 것 같습니다
말씀 감사드립니다!

2022-07-26 00:06 UTC, Lia316 commented on Hatnya/Screens/EditTask/EditTaskViewController.swift
> +        self.navigationController?.navigationBar.backgroundColor = .systemBackground
감사합니다!!

2022-07-26 00:07 UTC, Lia316 commented on Hatnya/Screens/EditTask/UIComponent/EditTaskSupplementaryView.swift
> +        ])
넵! 반영하겠습니다~

2022-07-26 01:42 UTC, Lia316 commented on Hatnya/Screens/EditTask/UIComponent/EditTaskSupplementaryView.swift
> +        ])
[5869f49](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/31/commits/5869f494075eac51941d6da52bf7353f95bbd021) 반영했습니다~

2022-07-26 01:55 UTC, Lia316 commented
@wonhui-kim  수정사항 반영 완료했습니다!

2022-07-26 02:19 UTC, MMMIIIN approved these changes
수고하셨습니다 ^_______^

2022-07-26 02:27 UTC, wonhui-kim approved these changes

2022-07-26 02:27 UTC, merged