Feature/35 create study segmented picker
DeveloperAcademy-POSTECH/MC3-Team1-Hatnya pull request #39
Opened 2022-07-26 06:31 UTC by kelly1422

## 작업내용
- [ ] uisegmentedcontrol로 변경
- [ ] picker뷰 삭제

![Simulator Screen Recording - iPhone 13 - 2022-07-26 at 15 25 19](https://user-images.githubusercontent.com/80809782/180938700-9100eff3-6cc9-4205-82c9-2eb4b03fc028.gif)

## 다음으로 진행될 작업
 - 뷰 컨트롤러 연결

## 참고한 코드 출처
https://calmone.tistory.com/entry/iOS-UIKit-in-Swift-4-UISegmentedControl-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

2022-07-26 10:25 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    let array = ["1주", "2주", "3주", "4주"]
p4;

enum으로 만들면 좋을 것 같아요 !
변수명도 더 명확히 할 수 있을 것 같아요 !

2022-07-26 10:26 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    private lazy var evryLabel: UILabel = {
p2;

오타가 있는 것 같군요...ㅎㅎ

2022-07-26 10:27 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +        print(selectedCycle)
p1;

print는 지워도 될 것 같아요 ! ^_____^

2022-07-26 10:29 UTC, MMMIIIN commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +        print(title(for: .selected) ?? "")
p1;

요기도 print 지워도 될 것 같아요 !

2022-07-26 13:40 UTC, wonhui-kim requested changes
수고하셨습니다!

2022-07-26 13:40 UTC, wonhui-kim commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    }()
p1;

외부에서 접근하지 않는다면 private 으로 변경해주시면 좋을 것 같아요!

2022-07-26 13:40 UTC, wonhui-kim commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    func segconChanged(segcon: UISegmentedControl) {
p4;

변수명을 줄이지 않고 명확하게 표현해주시면 좋을 것 같아요 😁

2022-07-26 14:39 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +        print(selectedCycle)
[f897d49](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/39/commits/f897d49a6d94516c2902924b6c77dad562f14d9f)
지웠습니다~!! 👍

2022-07-26 14:39 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +        print(title(for: .selected) ?? "")
[f897d49](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/39/commits/f897d49a6d94516c2902924b6c77dad562f14d9f)
지웠습니다~!!

2022-07-26 14:39 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    private lazy var evryLabel: UILabel = {
[81cac60](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/39/commits/81cac6086d90d3c774e9e4857d5e8d6ad55433cd)
날카로운 관찰력... 감삼당

2022-07-26 14:40 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    }()
[60391f5](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/39/commits/60391f54396e2cce85329caea2656c8f5b231537)
빼먹었네요 추가했습니다!

2022-07-26 14:40 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    func segconChanged(segcon: UISegmentedControl) {
[c7d0af0](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/39/commits/c7d0af05edd01e7e405af220f8ca570d2fe5ff5d)
한번 수정해보앗습니다!!

2022-07-26 14:41 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    let array = ["1주", "2주", "3주", "4주"]
[eb890a9](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/39/commits/eb890a96b0712d2ee7bbf188604db7f9a4e686b6)
일단 변수명은 명확히 바꾸어보았습니다!

2022-07-27 01:36 UTC, Lia316 reviewed
수고하셨습니다~!

final 과 private 키워드 코멘트가 반복적으로 나오는 것만 주의하시면 될 것 같습니다~!

2022-07-27 01:36 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    let cycleNameArray = ["1주", "2주", "3주", "4주"]
p3;

final & private

2022-07-27 01:36 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +        frame(forAlignmentRect: CGRect(x: 0, y: 0, width: 32, height: 32))
✨✨✨✨

2022-07-27 01:36 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/UIComponent/SelectCycleDaysView.swift
> +        }
✨✨✨✨

2022-07-27 02:02 UTC, wonhui-kim approved these changes

2022-07-27 02:05 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/CycleSegmentedControlView.swift
> +    let cycleNameArray = ["1주", "2주", "3주", "4주"]
[130835e](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/39/commits/130835eca63a342bd1512720db9414864524bf27)

[ad7c42e](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/39/commits/ad7c42e254525d429e3e468da9ca89bb13f5b48d)

수정했습니다. 다음엔 유의하고 처음부터 잘해봐야겠군여..

2022-07-27 02:05 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/DayButtonView.swift
> +        frame(forAlignmentRect: CGRect(x: 0, y: 0, width: 32, height: 32))
🔥🔥🔥🔥🔥🔥

2022-07-27 02:05 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/UIComponent/SelectCycleDaysView.swift
> +        }
🔥🔥🔥🔥

2022-07-27 02:31 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +        getStudyDescriptView.valueTextField.underlined(viewSize: getStudyDescriptView.valueTextField.bounds.width, color: .systemGray)
p3;

51번째 줄과 61번째 줄 린트 워닝 해결 부탁드립니다 ^__^

2022-07-27 02:56 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +        getStudyDescriptView.valueTextField.underlined(viewSize: getStudyDescriptView.valueTextField.bounds.width, color: .systemGray)
[316c2a4](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/39/commits/316c2a4f35a4bbdca30c7c0dfac56d2dd28d0ee5)

완료했숩니다~~!

2022-07-27 03:33 UTC, Lia316 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +        getStudyDescriptView.valueTextField.underlined(viewSize: getStudyDescriptView.valueTextField.bounds.width, color: .systemGray)
아하 이름을 바꿔서 해결하셨군요!

길어서 워닝을 띄우는 경우는, 
파라미터 간에 줄바꿈을 하여 해결하거나
배열의 요소 간에 줄바꿈을 하여 해결하는 방법도 있답니다! ^~^

2022-07-27 06:29 UTC, MMMIIIN approved these changes
수고하셨습니다 ^_______^

2022-07-27 07:19 UTC, kelly1422 commented on Hatnya/Screens/CreateStudy/CreateStudyViewController.swift
> +        getStudyDescriptView.valueTextField.underlined(viewSize: getStudyDescriptView.valueTextField.bounds.width, color: .systemGray)
줄바꿈을 해도 되겠군요! 다음에 너무 길어진다면 줄바꿈을 한번 해봐야겠어요 😲

2022-07-27 07:40 UTC, merged