[FEAT] StudyListView에서 StudyRoomView로 넘어가는 내비게이션 구현
DeveloperAcademy-POSTECH/MC3-Team1-Hatnya pull request #57
Opened 2022-07-29 03:41 UTC by unuhqueen

## 작업내용

![Simulator Screen Recording - iPhone 13 - 2022-07-29 at 12 36 49](https://user-images.githubusercontent.com/49133245/181677833-dbc9198d-853f-4b79-9376-b4229e8133f8.gif)

- [ ] StudyListView에서 StudyRoomView로 넘어가는 내비게이션 
- [ ] StudyListView에서 만들어진 StudyGroup 객체도 StudyRoomView에 같이 넘어가는 기능

## 리뷰포인트

- 생성한 StudyGroup 객체가 잘 넘어가는지 확인

## 다음으로 진행될 작업
 - 코드리뷰 및 Firebase 샘플데이터 작성

2022-07-29 07:07 UTC, Lia316 requested changes
수고하셨습니다~!

린트 워닝 확인하려고 프로젝트를 살펴보니,
지난번 PR에서 `StudyListViewController.swift`의 33, 95, 104번째 줄의 린트 워닝이 해결이 안 되어 있더라구요..!

이 부분까지 함께 수정 부탁드리며,
린트 워닝은 PR 올리시기 전에 확인 꼭 부탁드립니다!!

2022-07-29 07:07 UTC, Lia316 commented on Hatnya/Screens/StudyRoom/StudyRoomViewController.swift
>      }
p4;

studyGroup에 관한 목데이터를 하나 만드는 건 어떤가요?!

2022-07-29 07:07 UTC, Lia316 commented on Hatnya/Screens/StudyRoom/StudyRoomViewController.swift
> +
p3;

lint warning 해결 부탁드립니다~

2022-07-29 07:07 UTC, Lia316 commented on .swiftlint.yml
> +#    severity: error
p5;

lint 규칙을 수정할 때는, 수정하는 이유도 함께 PR에 설명해주시면 좋을 것 같습니다!

2022-07-29 09:41 UTC, MMMIIIN approved these changes
ㅋㅋㅋㅋㅋ 제 자동줄정리랑 겹쳐서 공백수정이 많네요... 후후
수고하셨습니다 ^______^ 이브 짱 👍

2022-07-30 14:40 UTC, unuhqueen commented
[4237f12](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/57/commits/4237f125df1f042199c4217c00bb2fbb657c62a8)
수정했습니다 approve 부탁드려용!

2022-07-30 14:42 UTC, unuhqueen commented
> 수고하셨습니다~!
> 
> 린트 워닝 확인하려고 프로젝트를 살펴보니, 지난번 PR에서 `StudyListViewController.swift`의 33, 95, 104번째 줄의 린트 워닝이 해결이 안 되어 있더라구요..!
> 
> 이 부분까지 함께 수정 부탁드리며, 린트 워닝은 PR 올리시기 전에 확인 꼭 부탁드립니다!!

[4237f12](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-Hatnya/pull/57/commits/4237f125df1f042199c4217c00bb2fbb657c62a8)
린트 워닝이랑 목데이터 수정했습니다!

2022-08-01 01:25 UTC, kelly1422 reviewed
수고하셨습니다~!!!!

2022-08-01 01:25 UTC, kelly1422 commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +                                                             createdAt: Date(), uid: studyGroupId))
q;

uid를 추가해 찾게 한 부분은 
같은 정보의 스터디가 있을수도 있어 문서값인 id로 접근하기 위함인가요!?

2022-08-01 01:25 UTC, kelly1422 commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +        navigationController?.pushViewController(studyRoomViewController, animated: true)
q; 

현재 뷰를 네비게이션뷰로 만들어주는 코드를 찾지 못한거 같은데,
현재 뷰컨인 스터디리스트뷰컨트롤러가 스토리보드상에서 네비게이션컨트롤러의 루트로 지정되어있어서 이렇게 사용이 가능한걸까요??

2022-08-01 04:01 UTC, Lia316 reviewed
리뷰 반영 감사드립니다! 

그러나 원 라스트 띵..!!

2022-08-01 04:01 UTC, Lia316 commented on Hatnya/Screens/StudyRoom/StudyRoomViewController.swift
> +        StudyRoomViewController(selectedStudyGroup: StudyGroup.sampleData[0]).toPreview()
👍🏻👍🏻👍🏻

2022-08-01 04:01 UTC, Lia316 commented on Hatnya/Screens/StudyRoom/StudyRoomViewController.swift
> +        preconditionFailure("init(coder:) has not been implemented")
p3;

`preconditionFailure`을 처음 알게 되었는데, 
찾아보니 이 친구도 `fatalError`처럼 런타임에서 에러를 받아 앱이 죽게 되는 코드인 것 같더라구요..!

`required init?(coder: NSCoder)`에 자동으로 fatalError가 있는 이유는 
'이 코드가 스토리보드로 작성할 때 호출되는 생성자이니, 스토리보드를 염두에 두고 꼭 쓰거라'
이런 느낌으로 알고 있어요.

그래서 저 에러를 남겨두기 보단, 다른 생성자처럼 내부에 코드를 작성해주는 것이 좋을 것 같습니다!

2022-08-01 07:00 UTC, unuhqueen commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +                                                             createdAt: Date(), uid: studyGroupId))
uid를 넣으면 firebase에 쿼리를 날릴 때 편해서 넣었습니다!

2022-08-01 07:00 UTC, unuhqueen commented on Hatnya/Screens/StudyList/StudyListViewController.swift
> +        navigationController?.pushViewController(studyRoomViewController, animated: true)
네네 맞습니당

2022-08-01 07:04 UTC, kelly1422 approved these changes
수고하셨습니다~!!!!

2022-08-01 07:51 UTC, Lia316 approved these changes

2022-08-01 07:52 UTC, merged